FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster==1.9.11 \
    dagster-webserver==1.9.11 \
    dagster-graphql==1.9.11 \
    dagster-postgres==1.9.11 \
    dagster-docker==1.9.11

ENV DAGSTER_HOME=/opt/dagster/dagster_home/
RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME
WORKDIR $DAGSTER_HOME
